### ISSUE TITLE
Octane water mixing example

### ISSUE THREAD

**Issue by SSchott** [khavernathy/mcmd#41]
I was testing the code, but the octane water cuda example, even though it ran, didn't show any movement on the octane molecules. Is this behaviour in any way intended, or I'm missing something?

Additionally, where can I find a list of commands and input formats aside from the examples and the source code? On the MPMC wiki, assuming this is written based on that? If using a PDB, how are the atom connections infered? Any note on PQR files?

**Comment by khavernathy** [comment]
Hi @SSchott ,

Let me take a look. In the meantime -- This code has a wiki too, with a list of commands and details about built-in potentials (see the navigation links on the right): https://github.com/khavernathy/mcmd/wiki

**Comment by khavernathy** [comment]
Turns out the example is best used with an older version of the code which by default excluded Ewald k-space contributions to force. I made an updated example input; you can get it from the git repo now.

MCMD's molecular dynamics features only rigid molecules; there are no bonding parameters (this is because we use it primarily for sorption of small gases in porous materials). We're working on constraint dynamics and bonding potentials now.

You can use .pdb/.pqr (there is no distinction in the code; the columns are read the same) for input atoms, per the examples. .xyz input is possible too but limited to use for frozen systems e.g. porous-material crystal lattices.

Please let us know if you run into other problems or have suggestions! This is a work in progress.

**Comment by SSchott** [comment]
Thanks for the prompt answer. It indeed works now but it takes over the GPU hard. Maybe add a warning for people using the same GPU for the X server. Also maybe adding the wiki file as a txt file would be a good idea. If I come across another issue I'll let you know.
